homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mqttbroker'

# Enable the Zigbee2MQTT frontend
frontend:
  port: 8080
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d0004850056':
    friendly_name: '0x00158d0004850056'